[package]
name = "connect4"
version = "0.1.0"
authors = ["Charles Cabergs <me@cacharle.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.5"
separator = "0.4.1"

[profile.release]
debug = 1
